## How Perceptron behaves with AND and NAND gate

In [41]:
import numpy as np
import pandas as panda
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

In [7]:
and_gate = np.array(

[
    
    [0,0,0,0],
    [0,0,1,0],
    [0,1,0,0],
    [0,1,1,0],
    [1,0,0,0],
    [1,0,1,0],
    [1,1,0,0],
    [1,1,1,1],
        
]

)

and_gate_table  = panda.DataFrame(and_gate)
and_gate_table.columns = ['x1','x2','x3','y']

and_gate_table

x1  x2  x3  y
0   0   0   0  0
1   0   0   1  0
2   0   1   0  0
3   0   1   1  0
4   1   0   0  0
5   1   0   1  0
6   1   1   0  0
7   1   1   1  1

In [9]:
xor_gate = np.array(

[
    
    [0,0,0,0],
    [0,0,1,1],
    [0,1,0,1],
    [0,1,1,0],
    [1,0,0,1],
    [1,0,1,0],
    [1,1,0,0],
    [1,1,1,1],
        
]

)

xor_gate_table  = panda.DataFrame(xor_gate)
xor_gate_table.columns = ['x1','x2','x3','y']
xor_gate_table

x1  x2  x3  y
0   0   0   0  0
1   0   0   1  1
2   0   1   0  1
3   0   1   1  0
4   1   0   0  1
5   1   0   1  0
6   1   1   0  0
7   1   1   1  1

In [97]:
classifier = Perceptron(eta0=0.01, max_iter = 100)


In [ ]:
x = and_gate_table.iloc[:,:3].values
y = and_gate_table.y.values

In [52]:
x,y

(array([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]]), array([0, 0, 0, 0, 0, 0, 0, 1]))

In [83]:

train_index = [1,2,3,4,x.shape[0]-1]
test_index = [i for i in range(x.shape[0]-1) if i not in train_index]
x_train = x[train_index]
y_train = y[train_index]

x_test = x[test_index]
y_test = y[test_index]



In [90]:
x_train, y_train

(array([[0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 1, 1]]), array([0, 0, 0, 0, 1]))

In [98]:
classifier.fit(x_train,y_train)

C:\Users\somak\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.01,
      fit_intercept=True, max_iter=100, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [99]:
x_test


array([[0, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [100]:
y_test

array([0, 0, 0])

In [102]:
classifier.predict(x_test)

array([0, 0, 0])

In [103]:
xor_gate_table

x1  x2  x3  y
0   0   0   0  0
1   0   0   1  1
2   0   1   0  1
3   0   1   1  0
4   1   0   0  1
5   1   0   1  0
6   1   1   0  0
7   1   1   1  1